name: Update Profile

on:

  push:
    branches:
      - master
  workflow_dispatch:

  # ┌─────────────────────────────────────┐
  # │          SECRETS REQUIRED           │
  # └─────────────────────────────────────┘
  # secrets.GITHUB_TOKEN

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run JSON Collector & Parser
        run: |  

            # Move into script DIR
            cd .github/workflows/scripts/

            # Add header readme onto the top.
            /bin/cat ../partials/README_HEAD.md > ./output.md

            # Install JQ
            sudo apt-get install jq

            # Run Repo collection
            ./repo_list.sh

            # Copy Results to README.md
            /bin/cat output.md >> ../../../README.md


      # Recommit Readme
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: README.md
            commit-msg: Update README
            github-token: ${{ secrets.GITHUB_TOKEN }}