name: Update Profile

on:

  push:
    branches:
      - master

  schedule:
    - cron:  '30 7,17 * * *'
    
  workflow_dispatch:
  
  # ┌─────────────────────────────────────┐
  # │          SECRETS REQUIRED           │
  # └─────────────────────────────────────┘
  # secrets.GITHUB_TOKEN

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run JSON Collector & Parser
        run: |  

            # Move into script DIR
            cd .github/workflows/scripts/

            # Run Repo collection
            ./repo_list.sh


      # Recommit Readme
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: README.md
            commit-msg: Update README
            github-token: ${{ secrets.GITHUB_TOKEN }}